version: '3'
services:
  jenkins:
    container_name: jenkins-master
    build:
      context: jenkins-master
    ports:
      - "8080:8080"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net
  production-server:
    container_name: production-server
    build:
      context: production-server
    networks:
      - net
networks:
  net:
